"""
Generates synthetic monthly spending records for training Masroof's
end-of-month projection model.

IMPORTANT: this data is SYNTHETIC. It is generated by the rules below, not
collected from real people. It exists so the projection model has something to
learn from on day one; it is not a claim about how real people spend.

Each synthetic user gets an income level, a set of category weights and a
spend-discipline parameter, then lives through 30 days of a month. We record
one partial observation per month (spend so far on a given day) and the final
total, which is exactly the shape of the problem the app has to solve at
runtime: "it is day 14, I have spent this much, what will I finish at?"

Run:  python model/generate_data.py
Out:  model/data.csv
"""

import numpy as np

SEED = 20260927
N_USERS = 4000
MONTH_DAYS = 30
OBSERVATIONS_PER_USER = 6

CATEGORIES = ["Food", "Transport", "Study", "Health", "Entertainment", "Other"]

# Typical amount for ONE transaction in each category, in whatever currency the
# app formats. These are absolute, not shares of anything.
BASE_COST = np.array([55.0, 30.0, 140.0, 95.0, 110.0, 70.0])

# Reference income the BASE_COST numbers were written for.
REF_INCOME = 6000.0

# Weekend is Friday and Saturday. `weekday` is 0 = Monday.
WEEKEND = {4, 5}


def make_users(rng, n):
    """One row per synthetic user: income, category taste, discipline."""
    income = np.round(rng.lognormal(mean=7.2, sigma=0.45, size=n)) + 900
    income = income.clip(1200, 45000)

    # Category preferences, Dirichlet so each user has a believable mix.
    taste = rng.dirichlet(np.full(len(CATEGORIES), 1.4), size=n)

    # How closely this user tracks their budget. Low discipline = spender.
    discipline = rng.beta(2.2, 2.8, size=n)

    # A monthly "flair" multiplier: some months are just expensive.
    flair = rng.lognormal(mean=0.0, sigma=0.22, size=n)

    return income, taste, discipline, flair


def category_rates(rng, user_income, taste, discipline):
    """
    Expected spend per transaction, per category, for one user.

    `taste` controls how OFTEN a category is picked (handled by the caller's
    probabilities), so it must not scale the amount. The amount comes from
    BASE_COST, nudged by how much the user earns and how disciplined they are.
    """
    # Amounts grow with income, but sub-linearly: richer people do not buy
    # proportionally bigger lunches.
    wealth = np.sqrt(user_income / REF_INCOME)
    wealth = float(np.clip(wealth, 0.45, 2.6))
    drag = 0.7 + 0.6 * discipline
    return BASE_COST * wealth * drag


def day_weight(day, weekday, flair, discipline):
    """
    How much a user tends to spend on a given day.

    - payday bump: days 1-3 and 26-30, people get paid and spend
    - weekend bump: Friday and Saturday
    - end-of-month dip: the last couple of days are usually quieter
    - flair: this month's overall mood
    - discipline: high-discipline users flatten their peaks
    """
    payday = 1.0
    if day <= 3 or day >= MONTH_DAYS - 4:
        payday = 1.45
    elif 13 <= day <= 15:
        payday = 1.18

    weekend = 1.3 if weekday in WEEKEND else 1.0
    dip = 0.8 if day >= MONTH_DAYS - 1 else 1.0

    # A disciplined user has less payday overshoot.
    payday = 1 + (payday - 1) * (1.4 - discipline)

    return payday * weekend * dip * flair


def simulate_user(rng, income, taste, discipline, month_flair):
    """Play out one month, return per-day totals for that user."""
    rates = category_rates(rng, income, taste, discipline)
    # Transaction count: more income means more transactions.
    daily_tx_mean = np.clip(1.1 + np.log1p(income) / 9.0, 1.0, 5.0)

    daily = np.zeros(MONTH_DAYS)
    daily_counts = np.zeros(MONTH_DAYS)
    category_spend = np.zeros(len(CATEGORIES))

    for day in range(1, MONTH_DAYS + 1):
        weekday = (day - 1) % 7
        w = day_weight(day, weekday, month_flair, discipline)

        n_tx = rng.poisson(daily_tx_mean * w * 0.6)
        if rng.random() < 0.12:  # occasional big day
            n_tx += rng.integers(2, 6)

        for _ in range(n_tx):
            cat = rng.choice(len(CATEGORIES), p=taste)
            # Log-normal amounts: many at the typical price, few much bigger.
            amount = np.round(rng.lognormal(np.log(rates[cat]), 0.6))
            amount = float(np.clip(amount, 5, max(income * 0.35, 20)))
            daily[day - 1] += amount
            daily_counts[day - 1] += 1
            category_spend[cat] += amount

    return daily, daily_counts, category_spend


def build_dataset():
    rng = np.random.default_rng(SEED)
    income, taste, discipline, flair = make_users(rng, N_USERS)

    rows = []
    for u in range(N_USERS):
        for _ in range(OBSERVATIONS_PER_USER):
            month_flair = flair[u] * rng.lognormal(0.0, 0.12)
            daily, counts, cat_spend = simulate_user(
                rng, income[u], taste[u], discipline[u], month_flair
            )
            full_total = daily.sum()

            # "Today" is never the last day of the month: that would make the
            # problem trivial.
            day = int(rng.integers(2, MONTH_DAYS))
            elapsed = day
            total_so_far = daily[:elapsed].sum()
            tx_so_far = counts[:elapsed].sum()
            top_cat = cat_spend.max()

            if total_so_far <= 0 or elapsed < 2:
                continue

            rows.append(
                {
                    "user": u,
                    "income": income[u],
                    "elapsed": elapsed,
                    "days_in_month": MONTH_DAYS,
                    "total_so_far": round(total_so_far, 2),
                    "tx_count": tx_so_far,
                    "top_category_share": round(top_cat / full_total, 4)
                    if full_total
                    else 0.0,
                    "n_categories": int((cat_spend > 0).sum()),
                    "full_month_total": round(full_total, 2),
                }
            )

    return rows


if __name__ == "__main__":
    import csv
    import os

    rows = build_dataset()
    out = os.path.join(os.path.dirname(__file__), "data.csv")
    with open(out, "w", newline="") as fh:
        writer = csv.DictWriter(fh, fieldnames=list(rows[0].keys()))
        writer.writeheader()
        writer.writerows(rows)

    totals = [r["full_month_total"] for r in rows]
    print(f"users: {N_USERS}   observations: {len(rows)}")
    print(f"monthly total: median {np.median(totals):.0f}  p90 {np.percentile(totals, 90):.0f}")
    print(f"wrote {out}")
