// GENERATED FILE - do not edit.
// Produced by model/train.py from synthetic data (model/generate_data.py).
// Inference lives in src/ml/predict.js.

export default {
  "_comment": "Generated by model/train.py from synthetic data (model/generate_data.py). Do not edit by hand. Inference lives in src/ml/predict.js.",
  "features": [
    "frac",
    "daily",
    "daily_x_frac",
    "daily_x_frac2",
    "daily_x_remaining_frac",
    "log_daily",
    "tx_per_day",
    "top_category_share",
    "n_categories",
    "log_income",
    "spent_over_income",
    "is_weekend_start"
  ],
  "intercept": -6495.991155535754,
  "coefficients": [
    -2903.367470961755,
    13.089947269726956,
    20.749275404237096,
    -9.926832667331121,
    -7.65932813463031,
    23.169254069264433,
    -104.47196939779693,
    665.7694976940251,
    130.91567157971062,
    1039.8517768540237,
    660.1961846804419,
    63.79890495026207
  ],
  "training": {
    "synthetic_users": 4000,
    "train_rows": 19175,
    "test_rows": 4792,
    "mae": 460.8,
    "naive_mae": 648.4,
    "improvement_pct": 28.9,
    "mape": 14.9
  }
};
