// GENERATED FILE - do not edit.
// Produced by model/train.py from synthetic data (model/generate_data.py).
// Inference lives in src/ml/predict.js.

export default {
  "_comment": "Generated by model/train.py from synthetic data (model/generate_data.py). Do not edit by hand. Inference lives in src/ml/predict.js.",
  "features": [
    "frac",
    "daily",
    "daily_x_frac",
    "daily_x_frac2",
    "daily_x_remaining_frac",
    "log_daily",
    "tx_per_day",
    "top_category_share",
    "n_categories",
    "log_income",
    "spent_over_income",
    "is_month_end"
  ],
  "intercept": -9912.303778215843,
  "coefficients": [
    -4779.884531356996,
    16.40610064423556,
    23.05420045268282,
    -12.825126368620637,
    -6.648099809344178,
    -633.318799951839,
    -225.8852604570111,
    1118.0922324796497,
    243.20722974718242,
    1744.2617792278202,
    1764.3764565465467,
    157.26480423783346
  ],
  "feature_ranges": {
    "frac": [
      0.066667,
      0.966667
    ],
    "daily": [
      2.0,
      1404.0
    ],
    "daily_x_frac": [
      0.266667,
      864.166667
    ],
    "daily_x_frac2": [
      0.026667,
      720.138889
    ],
    "daily_x_remaining_frac": [
      1.23908,
      1310.4
    ],
    "log_daily": [
      1.098612,
      7.247793
    ],
    "tx_per_day": [
      0.2,
      7.0
    ],
    "top_category_share": [
      0.2052,
      0.9338
    ],
    "n_categories": [
      3.0,
      6.0
    ],
    "log_income": [
      7.09091,
      11.002117
    ],
    "spent_over_income": [
      0.00111,
      3.745
    ],
    "is_month_end": [
      0.0,
      1.0
    ]
  },
  "training": {
    "synthetic_users": 4000,
    "train_rows": 19173,
    "test_rows": 4792,
    "mae": 838.9,
    "naive_mae": 1146.7,
    "improvement_pct": 26.8,
    "mape": 15.9
  }
};
